### ISSUE TITLE
Can't install due to "addon does not have correct structure"

### ISSUE THREAD

**Issue by MrMEEE** [tuxfuxch/yarc#1]
Hi

When trying to install your plugin on Kodi 15 (Isengard), I get a "addon does not have correct structure", when downloading and installing the zip file...

Any help would be appreciated...

**Comment by tuxfuxch** [comment]
Hi MrMEEE!
Thanks for the report. Unfortunately tomorrow is national day in my country and i am off to the mountains for the weekend.  So Monday i can have a look into it. But a Workaround if you want to try before:
**\* WARNING: this is totally not recommended. for a nuclear meltdown i don't take any responsibility. ***
but if you are good with "computerz and such" you can try the following (i don't know the consequences. Anyhow, i did never find any):
locate the data folder (in linux it might be ~/.kodi/addons) make a folder "webinterface.yarc" there. unpack the content from the folder "yarc-master" (everything in there... some files and folders) from the downloaded zip there). restart kodi and the plugin should apear.

EDIT: the location is the same place as the userdata folder described here: http://kodi.wiki/view/Userdata (and from

**Comment by MrMEEE** [comment]
I tried that.. but the plugin doesn't show up afterwards..

**Comment by tuxfuxch** [comment]
Hi,
i was on an old version (still xbmc) and there i could install the plugin. then i updated to test with 15.1 where it did not work. also my "trick" did not work as you told me. i am still investigating. sorry to ask for patience, i have other stuff to do too ;) 
as soon as i know more i will post here.

**Comment by ricardofcf** [comment]
Adding `<extension point="xbmc.addon.metadata">` to addon.xml makes yarc work (mostly) in Isengard.

**Comment by MrMEEE** [comment]
Still getting the same error, when I try to install..

**Comment by tuxfuxch** [comment]
Hi
Did not have that much time recently, but i spent already hours on this issue. Same here, does not work for me. Anyway thanks for the tip, and i try some things around it.
@recardofcf: what do you mean with mostly?

**Comment by ricardofcf** [comment]
It works if you change `<extension point="xbmc.gui.webinterface"/>` to `<extension point="xbmc.webinterface"/>`. Sorry, forgot about that. 
@tuxfuxch When I use the navigation arrows, it sends multiple inputs at once. It's like the button gets stuck. Also, when I use the "touchpad", it sometimes fails to either recognize the gesture or send the input. Other than that, some add-ons don't have an icon.png and yarc should use a generic one (it breaks page formatting), but that's more of a suggestion...

**Comment by tuxfuxch** [comment]
Hey Guy's! 

Hours later it works. ricardofcf's tip helped (thanks!), but seemed to be not the only problem in my current version.
@ricardofcf : The prevpic  and the button problem should be solved. about the "touchpad", i don't know, really, for me it works perfectly. if you want, please make a new thread, also with version, browser etc.

The current version is in the ZIP uploaded! 
Also be aware, that i did not test very carefully, and since under the hood changed a lot, there could be bugs. In case, i apologise. I thought a poorly working solution is better than none :)
