### ISSUE TITLE
Disable "send text" option

### ISSUE THREAD

**Issue by DanielTizon** [tuxfuxch/yarc#5]
Hi,

Im pleased to see so a nice work done with yarc. I was going crazy trying to find a web interface for kodi that I could use in my smartphone. And I finally found it, thanks guy :+1: 

There is a little thing that I would like, to be able to disable the "send text" option of the main windows. I am using this web interface embedded in another application and it takes too much space, it would be possible to give a option of disable it from configuration panel?

Thanks

and keep the nice work!!!

**Comment by tuxfuxch** [comment]
EDIT: forget this, read next comment!

Hi Daniel,
yes, i will do that for the next version, but the new version will not come in the next day's no promises when. but it's quite simple and i can imagine that others would like to see that too.
Meanwhile you can disable it manually:
go to the addonfolder yarc in kodi. open index.html in an editor and find the following lines: 

``` html
<div id="SendText" class="ui-grid-b">
<div class="ui-block-a"><input id="SendTextField" name="SendTextField" type="text" placeholder="Send Text"></div>
<div class="ui-block-b"><a id="SendTextButton" data-role="button"><span data-yts="SEND_TEXT"></span></a></div>
</div>
```

delete them, or uncomment it (put "" after it). so you don't have to wait. 
in the next version you will find it in the settings in the "Remote" section.

**Comment by tuxfuxch** [comment]
please forget what i wrote, that would be very bad practise. 
not perfect but quick and better would be:

open in the yarc addonfolder the file /resources/css/styles.css and put in the beginning the line:
(best right after the tilte "General (G)")

``` css
#SendText {
    display: none;
}
```

oh and thanks for the nice words. i'll try :)

**Comment by tuxfuxch** [comment]
Hi Again,

ok i implemented it. it will come with the next version 0.9.12 (probably in the beginning of the next year)

unfortunatelly the implementaion messed up the config. hope i can manage it, that it happens not in the release.

**Comment by DanielTizon** [comment]
Nice tuxfuxch, thx!!
