### ISSUE TITLE
http://zc.qq.com

### ISSUE THREAD

**Issue by ricardofcf** [tuxfuxch/yarc#7]
I'm seeing this error on my kodi.log while idle.

> 21:20:09 39118.523438 T:1396700176 WARNING: Create - unsupported protocol(/home/pi/.kodi/addons/webinterface.yarc/http) in /home/pi/.kodi/addons/webinterface.yarc/http://zc.qq.com/cgi-bin/common/attr
> 21:20:09 39118.527344 T:1396700176   ERROR: Exists - Error checking for /home/pi/.kodi/addons/webinterface.yarc/http://zc.qq.com/cgi-bin/common/attr
> 21:20:09 39118.531250 T:1396700176 WARNING: CreateLoader - unsupported protocol(/home/pi/.kodi/addons/webinterface.yarc/http) in /home/pi/.kodi/addons/webinterface.yarc/http://zc.qq.com/cgi-bin/common/attr

Any ideas?

**Comment by tuxfuxch** [comment]
hey shelkr,
hm... unfortunately i have not a clue. i don't have them in my log's (i looked into two) and can't imageine where it comes from. i don't do any cgi stuff. in the internet, some sites, suggests that could be something nasty.
the protocoll i am using are http, some ftp, and some kodi stuff like "image://".
do you have this folers in /home/pi/.kodi/addons/webinterface.yarc? where could they come from, in case they do exist?
do you use something newer then yarc 0.7.1?

edit: if you are on the latest yarc release, if you have in the settings the image quality on 95, does it still show this log entries?

**Comment by tuxfuxch** [comment]
hi sheikr,

it's still a mystery to me. do you have any updates?

**Comment by ricardofcf** [comment]
Hey @tuxfuxch 

Sorry for my late answer. I've been searching for a possible cause and it is mostly likely due to the fact that I have my RPi2 as a DMZ host. I've also seen these "attacks" on a number of honeypot servers, even though I can't fully understand what it is trying to do. The only difference in this case is that yarc is getting in the way and writes that to the kodi log... Regarding your questions, I'm running the latest version from here on GitHub and run it with default settings (apart from language).

Thank you!
